# Generated by Django 3.0.3 on 2020-08-31 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200831_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='actual_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_active_bid', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/<django.db.models.fields.CharField>'),
        ),
    ]
