# Generated by Django 3.0.3 on 2020-09-05 19:45

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200902_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[auctions.models.positive_decimal_field]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[auctions.models.positive_decimal_field]),
        ),
    ]
