# Generated by Django 3.0.3 on 2020-09-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200906_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='image_URL',
        ),
    ]
